export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";

export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";

// export const POST_ERROR = "POST_ERROR";

export const UPDATE_LIKE_REQUEST = "UPDATE_LIKE_REQUEST";
export const UPDATE_LIKE_FAIL = "UPDATE_LIKE_FAIL";
export const UPDATE_LIKE_SUCCESS = "UPDATE_LIKE_SUCCESS";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_FAIL = "GET_POST_FAIL";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_FAIL = "ADD_POST_FAIL";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const REMOVE_COMMENT_REQUEST = "REMOVE_COMMENT_REQUEST";
export const REMOVE_COMMENT_FAIL = "REMOVE_COMMENT_FAIL";
export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS";
